from dotenv import load_dotenv
from langchain.chat_models import init_chat_model
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.messages import AIMessage,HumanMessage,SystemMessage
from langchain_core.output_parsers import StrOutputParser
from pydantic import BaseModel,Field
from langchain_openai import ChatOpenAI
from langchain_anthropic import ChatAnthropic
import time



load_dotenv()

llm  = init_chat_model(model="gpt-4o-mini")
openai_llm =  ChatOpenAI(model="gpt-4o-mini")
anthropic_llm = ChatAnthropic(model="claude-haiku-4-5-20251001")
resilient_llm = openai_llm.with_fallbacks([anthropic_llm])

questions = [
    {"question": "Who directed Baahubali?"},
    {"question": "What is the capital of Japan?"},
    {"question": "Explain gravity in one sentence."},
    {"question": "Who wrote Hamlet?"},
    {"question": "What is 15 * 14?"}
]




class QAresponse(BaseModel):
    answer: str = Field(
        description="Final answer text generated by the AI system"
    )
    confidence: float = Field(
        description="Confidence score (0.0–1.0) indicating how reliable the answer is",
        ge=0.0,
        le=1.0
    )
    sources: list[str] = Field(
        description="List of source references (URLs, docs, or citations) used to support the answer"
    )


structured_llm  = resilient_llm.with_structured_output(QAresponse)



prompt = ChatPromptTemplate.from_messages([
    ("system", "you are helpful and knowledge ai assistant with telugu film industry knowledge tfi banisa"),
    ("human", "{question}")
])

chain = prompt | structured_llm
streaming_chain = prompt | structured_llm

start_seq = time.perf_counter()
seq_results = []

for q in questions:
    seq_results.append(streaming_chain.invoke(q))
seq_time = time.perf_counter() - start_seq

print(seq_results)
print('-'*80)
print(seq_time)

# 2. Batch Timing (Concurrent with max_concurrency: 3)
start_batch = time.perf_counter()
batch_results = streaming_chain.batch(questions, config={"max_concurrency": 3})
batch_time = time.perf_counter() - start_batch

print(f"Batch Time     : {batch_time:.2f} seconds (Faster!)")